name: WorldTP
main: org.interguild.WorldTP
version: 1.1.1
softdepend:
- Multiverse-Core
commands:
  wtp:
    description: WorldTP - Conveniently teleport across Survival and Creative worlds without losing your place.
    usage: /wtp (creative | survival | c | s)
